title: >
  thetredev / <br/>knowledge base
description: Collection of things I've learned so far
theme: just-the-docs

url: https://thetredev.github.io/knowledge-base
color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d at %H:%M"
